name: Python package

on:
  push:
    tags:
      - qi-python-v*
  workflow_dispatch:

jobs:
  build_wheel:
    runs-on:
      - ubuntu-latest
      - macos-13
      - macos-latest
      - windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python (3.12)
      uses: actions/setup-python@v3
      with:
        python-version: 3.12
    - name: Install dependencies
      run: python -m pip install "cibuildwheel>=2"
    - name: Run cibuildwheel
      run: cibuildwheel --output-dir wheelhouse
